### ISSUE TITLE
Crash with Tree Chopper

### ISSUE THREAD

**Issue by DatrixTHLK** [DuchLord/TreeChopper#17]
Just opened minecraft and CTD. It is possible that there is a mod that doesn't exactly get along with Tree Chopper. 
Minecraft 1.10.2
Forge 12.18.1.2094
Tree Chopper: 1.1.0
Crash Report: http://pastebin.com/YESxLAER

**Comment by DuchLord** [comment]
Well I know exactly where the problem is.. The thing is some of your mod is trying to open network channel between server and client, with the name that already exist. I have to rename my channel to more complicated name, than "MyChannel" :D

**Comment by DatrixTHLK** [comment]
Assuming I don't understand what you're saying. Why would a mod need to open a network channel between client and server?

**Comment by DuchLord** [comment]
My channel is for sending server settings to client. (BreakSpeed is completly client side). The data are sending on client connect and on command /tch breakspeed value, which change breakSpeed in running game.

**Comment by DatrixTHLK** [comment]
I see. Thanks for further explaining it.
