### ISSUE TITLE
Unable to craft

### ISSUE THREAD

**Issue by BloodyDisaster** [DuchLord/TreeChopper#22]
With this mod installed I am unable to craft sticks and a crafting bench, after working with a few friends we have found the same problem

**Comment by DuchLord** [comment]
Hello,

wow I see, but I am unable to craft anything in a inventory, with or without my mod.. There is something wrong with minecraft forge. Please try it without my mod.

**Comment by DuchLord** [comment]
Ok, try to upgrade minecraft forge, it has been fixed.. (13.19.0.2153)
