### ISSUE TITLE
Unable to chop down dark oak with custom item

### ISSUE THREAD

**Issue by Daenara** [DuchLord/TreeChopper#30]
Hello,

we plax on a server with IndustrialCraft2 on 1.10.2 and we added the chainsaw to the mod config. I can chop down trees just fine with it but dark oak doesn't seem to work. I don't get a notification in chat and only get one block, not the whole tree. 

It might be an issue with the chainsaw not having durability in the normal sence. It is a charchable item that works fast as long as it has energy, if it runs out it is slow but still works. Could you please look into it?

Daenara

**Comment by DuchLord** [comment]
Hello,

yes I will look in to it, but right now, I am busy with school :(

**Comment by Daenara** [comment]
Not a problem, I just have to keep crafting axes to chop down big trees. Just look into it when you find time.

**Comment by DuchLord** [comment]
Hello,

I just tested your problem and it works fine for me.. 
If you have a fuel, you can chop down a tree, but if you doesn't have enough fuel, you are able to break just one block.

Tested on several variants of wood.
