### ISSUE TITLE
Bug: Obsidian Tools & Armor 

### ISSUE THREAD

**Issue by BiatuAutMiahn** [DuchLord/TreeChopper#34]
The axe in the Obsidian Tools & Armor  Mod does not work

Edit:
I added "item.obsidian_axe" to the config with no effect

**Comment by DuchLord** [comment]
Hello,

you have wrong spelled names. Please use in-game command "/tch printname 1" for name printing.

**item.obsidianaxe
item.emeraldaxe
item.emeraldsuperaxe
item.obsidiansuperaxe**
