### ISSUE TITLE
Version 1.12 crash

### ISSUE THREAD

**Issue by darrenhollick** [DuchLord/TreeChopper#47]
Hello,

I have setup a brand new Forge 1.12 server and only installed this mod.  The server crash report is attached.
[crash-2017-06-27_17.29.44-server.txt](https://github.com/DuchLord/TreeChopper/files/1106891/crash-2017-06-27_17.29.44-server.txt)

Do you think you could update for version 1.12?

**Comment by DuchLord** [comment]
Hello,

the mod is ready for 1.12, but I need to make some testing. I will release actual version of mod, using forge 1.12-14.21.0.2375.

**Comment by DuchLord** [comment]
https://github.com/DuchLord/TreeChopper/releases/tag/1.2.0a

**Comment by darrenhollick** [comment]
Holy crap that was fast!  Thanks for being awesome!

**Comment by darrenhollick** [comment]
I've been doing some testing with that version and I did just find what I think is a bug.  I was testing chopping down each kind of tree and found a dark oak forest (I think that's the one... huge trees with vines all over them 2x2 trunks) and when clicking on the bottom of one of the big trees the server paused for a long time then crashed... the crash report is attached.
[crash-2017-06-27_18.51.12-server.txt](https://github.com/DuchLord/TreeChopper/files/1107059/crash-2017-06-27_18.51.12-server.txt)

**Comment by DuchLord** [comment]
Ok I see

Thanks for help.

**Comment by DuchLord** [comment]
It should be fine now :)
