### ISSUE TITLE
TreeChopper not working on server

### ISSUE THREAD

**Issue by HenrikoMagnifico** [DuchLord/TreeChopper#49]
Currently playing on a Forge 14.21.0.2340 server, and TreeChopper doesn't work. I have the mod installed both server-side and client-side. I am also using FTBLib and FTBUtilities, but removing them doesn't solve the problem.

**Comment by DuchLord** [comment]
Hello,
please try to update your forge. Your version (14.21.0.2340) is still a beta. The recommended forge version is 14.21.1.2387. Let me know

**Comment by HenrikoMagnifico** [comment]
I will try that!

**Comment by DuchLord** [comment]
Fixed
