### ISSUE TITLE
Tree Chopper Causing Error In FTBLib/FTBUtilties Server Info Command

### ISSUE THREAD

**Issue by V3xatious** [DuchLord/TreeChopper#50]
Hello!
I know normally, I wouldn't post a compatibility issue, but seeing as it's FTBLib and what would be in all the FTB packs, so I thought you might take an interest.

Forge 2400
FTBLib 4.0.5 and FTBUtilities 4.0.3
Tree Chopper 1.2.1 for 1.12

There is a conflict between Tree Chopper and the "Server Info" button.  
Code below.
`12:36:57 [Warn] Couldn't process command: ftb server_infojava.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n at treechopper.common.command.TCHCommand.func_71518_a(TCHCommand.java:35) ~[TCHCommand.class:?] at com.feed_the_beast.ftbu.ranks.CmdOverride.func_71518_a(CmdOverride.java:58) ~[CmdOverride.class:?] at com.feed_the_beast.ftbu.ServerInfoPage.addCommandUsage(ServerInfoPage.java:209) ~[ServerInfoPage.class:?] at com.feed_the_beast.ftbu.ServerInfoPage.getPageForPlayer(ServerInfoPage.java:166) ~[ServerInfoPage.class:?] at com.feed_the_beast.ftbu.cmd.CmdServerInfo.func_184881_a(CmdServerInfo.java:25) ~[CmdServerInfo.class:?] at com.feed_the_beast.ftbu.ranks.CmdOverride.func_184881_a(CmdOverride.java:70) ~[CmdOverride.class:?] at net.minecraftforge.server.command.CommandTreeBase.func_184881_a(CommandTreeBase.java:149) ~[CommandTreeBase.class:?] at com.feed_the_beast.ftbu.ranks.CmdOverride.func_184881_a(CmdOverride.java:70) ~[CmdOverride.class:?] at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?] at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?] at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:948) [oy.class:?] at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:927) [oy.class:?] at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?] at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?] at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102] at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) [MinecraftServer.class:?] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:391) [nx.class:?] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665) [MinecraftServer.class:?] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523) [MinecraftServer.class:?] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]`

If this does not interest you, then I apologize for wasting your time, and go ahead and close this. (:

**Comment by DuchLord** [comment]
Hi,

tested with:
Forge 1.12.1-14.22.0.2459
MC 1.12.1
FTBLib-4.0.5
FTBUtilities-4.0.3
TreeChopper 1.12.1-1.2.2

and everything works :)
