### ISSUE TITLE
Does not work on personalised hatchet

### ISSUE THREAD

**Issue by phlnx** [DuchLord/TreeChopper#51]
Hello,

Minecraft 1.12 (latest version as to the date of this issue)
Forge 1.12.-14.21.1.2387, also tried with .2420
TreeChopper 1.12-1.2.1
Config unchanged

TreeChopper works perfectly on any freshly crafted stone axe.

However it does _not_ work on my custom made, Command-block spawned Diamond axe, although when I use printName it does register as **item:item.hatchetDiamond**.

Back with MC 1.11.2 and tree chopper 1.11.2-1.1.2 it worked perfectly.

This is the command block command I used to spawn my custom made axe, whose main feature is that it is unbreakable.

/give @p diamond_axe 1 0 {display:{Name:"My Axe"},ench:[{id:32,lvl:5},{id:35,lvl:5}],Unbreakable:1}

To reiterate, everything else being the same, with MC 1.11.2 and Tree Chopper 1.11.2-1.1.2, the very same world, the very same player, the very same axe, everything worked perfectly. I updated to 1.12 and it doesn't - with that axe. It does with any vanilla axe.

Thank you for your help.

**Comment by DuchLord** [comment]
Hello,

thank you for report, but it works fine for me :(

https://imgur.com/a/b0Mfm

**Comment by phlnx** [comment]
Hey DuchLord,

Thank you for reading and testing my issue. Do you have any suggestions as of things I could do or information I could share to pinpoint the cause?

One thing I noticed is that TreeChopper now appears to have its config file in its own folder but previously it was floating in the config folder. Could the presence of both files hinder the correct functioning of the mod? Should I delete the previous file? If I delete both, will TreeChopper recreate a file in the correct location?

**Comment by DuchLord** [comment]
I have a few more ideas about that problem. I will do some more tests :)

Yes of course, you can delete it. The mod will create a new one automatically.

**Comment by phlnx** [comment]
So, update. Up until now I was using the axe I had in 1.11 and that was carried over to 1.12 when I updated MC but kept the old world and the old player.

I tried "crafting" a new axe with the very same command I gave you, and this new axe works. So I think the ticket can be closed. I guess the only way for you to try it would be to play with 1.11.2, craft the axe, then update to 1.12 (minecraft and your mod) and then try it there. I'd be the first to say that it's probably not worth it.

I'm going to keep the old axe, in case you need information for me to study the issue furtherly but from my point of view the ticket can be closed.

Thank you for your help.

**Comment by phlnx** [comment]
I apologize for reopening this, but suddenly the mod isn't working anymore and it is showing the same symptoms as it did before:

- The old axe just does not activate the mod at all
- A brand new axe, either crafted or spawned, activates the mod

I have a feeling that TreeChopper either calculates or determines the axe's durability regardless of it being unbreakable and once the axe is deemed to have no durability left, it just stops working. It's just a hunch because there is no error or warning message anywhere.

I remember in an old version there was a setting to avoid this determination but I can't find it now in the config file.

As always thank you for your attention.

**Comment by DuchLord** [comment]
Hello,

I have decited to remove this option as well as alert message which tells you that you have not enough axe durability.

If you hit wooden block, the mod checks if player have enough axe durability to chop every single block:

- If axe durability > or = to block count (plus some numbers :D) the mod will activate.
- If not, it just break one single block.

People often complains about that spammy message, that you dont have enought axe durability.

**Comment by phlnx** [comment]
Hey, thank you for your reply.

I suspected as such, it was the only possible explanation that made sense out of what I what experiencing. I also suspect TreeChopper does not make an unbreakability check. I do not have experience in coding MC mods, but I would tentatively guess that such a check would be all that's needed to close this issue.

Meanwhile I moved to TreeCapitator which works. But I'll be happy to come back to TreeChopper once the issue is resolved :)

**Comment by DuchLord** [comment]
I'll come up with something :)

**Comment by DuchLord** [comment]
I have made some changes, you can try it, if you want.

https://github.com/DuchLord/TreeChopper/releases/download/1.2.2/TreeChopper-1.12-1.2.2.jar

Thanks

**Comment by phlnx** [comment]
Thank you, it seems to be working now.
