### ISSUE TITLE
Add HarvestCraft compatibility?

### ISSUE THREAD

**Issue by CREEATION** [DuchLord/TreeChopper#53]
See the following image: http://imgur.com/a/zDFvZ
They just float in the air. Any chance you can add compatibility for HarvestCraft?

https://minecraft.curseforge.com/projects/pams-harvestcraft

**Comment by DuchLord** [comment]
Hello,

yes I will look into it.

**Comment by DuchLord** [comment]
Done.

**Comment by CREEATION** [comment]
Wow, will update. Thanks! <3
