### ISSUE TITLE
Ore Dictionary Integration

### ISSUE THREAD

**Issue by FlaggedBrad** [DuchLord/TreeChopper#54]
Hi, as you can see: most, if not all, of the wood logs in the game have the "logWood" ore dictionary tag. If you could use this instead of independent block ids, it would work with every mod supporting the ore dictionary. Also, if you use standardized item ids inside the config file instead of tile ids, that would probaby be better. The reason i'm asking for this, is because i can't for the life of me get sakura trees from forestry to work with this mod.
![image](https://user-images.githubusercontent.com/18545011/28799960-8e6550da-75ff-11e7-827b-6a002116812a.png)

**Comment by DuchLord** [comment]
Hello,

this feature is already implemented since 1.2 version. However this is not very reliable, because not every modder tag his wood with WOOD tag :( This is the main reason for name identification.

Plus if you add e.g. stone block, it will work for stone.
