### ISSUE TITLE
Not working on Vanilla server

### ISSUE THREAD

**Issue by FaizanDurrani** [DuchLord/TreeChopper#60]
According to the description of the mod on CurseForge, it should work on Vanilla as it is a client-side mod. However, it doesn't work. The time taken to chop the base wood is increased but it does not bring down the whole tree, just the one log that was being broken

MC: v1.12.2
FML: v1.12.2-forge1.12.2-14.23.0.2515
MOD: v1.2.4

**Comment by DuchLord** [comment]
Hello,
I see.. The description is quite weird :D 
If you want to run the mod on a server, than server-side is required (server needs to run that mod).
